project:
  type: website
  # If you want to bypass the site folder so that files are directly transfered to
  # docs file and when we do quarto render it will automatically be pushed to github.
  output-dir: docs/ 

website:
  title: "DSCI521_website-test1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



